// GENERATED by scripts/sync-shapes.mjs — do not edit by hand.
//
// Copied from remotion-app/src/wrongshape/shapes.ts, which is the authored source and
// is shared with the Wrong-Shape Machine video. Edit it there, then run:
//
//     bun run sync
//
// Committed rather than gitignored so this project builds without the Remotion project
// checked out alongside it.

/**
 * The four shapes, as polygons.
 *
 * Everything is a polygon, including the circle (a 48-gon, visually perfect at this
 * size). One representation means the block and the hole are literally the same
 * data at two scales, so a block can never be a slightly different shape from the
 * hole it is supposed to fit — which in a video about whether things fit would be
 * the worst possible bug.
 *
 * THE BLOCKS ARE ALL ONE COLOUR, AND THAT IS THE POINT.
 *
 * Real shape-sorter toys colour-code their shapes, and the first draft of this file
 * did too — red circle, blue square, green triangle, yellow star. It is prettier and
 * it is pedagogically broken: given a colour cue, a three-year-old solves the puzzle
 * by matching colour to colour and never looks at the shape once. The video would
 * have taught colours, which is the Sorting Factory's job, and taught nothing about
 * shape.
 *
 * With one colour, outline is the only available signal. Do not "improve" this.
 */

export type ShapeId = "circle" | "square" | "triangle" | "star";

export type Shape = {
  id: ShapeId;
  /** Drawn on screen; uppercased by the renderer. */
  word: string;
  /** Unit polygon in a 100x100 box, centred on (50, 50). */
  points: [number, number][];
};

const polar = (
  cx: number,
  cy: number,
  r: number,
  degrees: number,
): [number, number] => {
  const rad = (degrees * Math.PI) / 180;
  return [cx + r * Math.cos(rad), cy + r * Math.sin(rad)];
};

const circlePoints = (r: number, segments = 48): [number, number][] =>
  Array.from({ length: segments }, (_, i) =>
    polar(50, 50, r, (i * 360) / segments),
  );

const starPoints = (
  outer: number,
  inner: number,
  arms = 5,
): [number, number][] =>
  Array.from({ length: arms * 2 }, (_, i) =>
    polar(50, 50, i % 2 === 0 ? outer : inner, -90 + (i * 180) / arms),
  );

/**
 * Fixed left-to-right order on the board, in every episode of the series.
 *
 * Same promise as the Sorting Factory's bin order: a returning child can start
 * answering by position before they can answer by shape, which is a real
 * intermediate step and not cheating. Reordering this reorders the whole series.
 */
export const SHAPES: Shape[] = [
  { id: "circle", word: "Circle", points: circlePoints(42) },
  {
    id: "square",
    // Sharp corners, not rounded. Rounded reads friendlier and blurs the one
    // feature that distinguishes it from the circle at a glance.
    word: "Square",
    points: [
      [12, 12],
      [88, 12],
      [88, 88],
      [12, 88],
    ],
  },
  {
    id: "triangle",
    word: "Triangle",
    points: [
      [50, 8],
      [92, 86],
      [8, 86],
    ],
  },
  { id: "star", word: "Star", points: starPoints(46, 20) },
];

export const shapeById = (id: ShapeId): Shape => {
  const found = SHAPES.find((s) => s.id === id);
  if (!found) throw new Error(`Unknown shape "${id}"`);
  return found;
};

export const shapeIndex = (id: ShapeId): number =>
  SHAPES.findIndex((s) => s.id === id);

/** Scales a unit polygon about the centre of its box and emits an SVG points list. */
export const scaledPoints = (
  shape: Shape,
  scale: number,
): [number, number][] =>
  shape.points.map(([x, y]) => [50 + (x - 50) * scale, 50 + (y - 50) * scale]);

export const pointsAttr = (points: [number, number][]): string =>
  points.map(([x, y]) => `${x.toFixed(2)},${y.toFixed(2)}`).join(" ");

/**
 * The hole is the same polygon, slightly larger than the block.
 *
 * 1.16 is a deliberate, visible gap. A hole exactly the size of the block reads as
 * a printed outline rather than an opening, and the moment the block sinks into it
 * stops being legible.
 */
export const HOLE_SCALE = 1.16;
