/**
 * Copies the shape polygons from the Remotion project into src/shared/shapes.ts.
 *
 *   bun run sync            # write the copy
 *   bun run sync --check    # fail if the copy is stale (for CI)
 *
 * WHY THIS EXISTS: the game used to import
 * `../../remotion-app/src/wrongshape/shapes.ts` directly, which kept exactly one
 * definition of what a circle, square, triangle and star are — but it also meant the
 * game could not be built without the sibling project present. Any deploy that checks
 * out only this folder fails at `tsc` with "Cannot find module". Verified, not assumed.
 *
 * So the authored source stays in the Remotion project and the copy here is generated
 * and committed, the same pattern the video pipeline already uses for `audio-durations.ts`.
 * The copy being committed is what makes CI work; `--check` is what stops it silently
 * going stale.
 *
 * If the two ever disagree, the Remotion project wins — edit there, run this, commit.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const SOURCE = resolve(root, "..", "remotion-app", "src", "wrongshape", "shapes.ts");
const OUT_DIR = join(root, "src", "shared");
const OUT = join(OUT_DIR, "shapes.ts");

const HEADER = `// GENERATED by scripts/sync-shapes.mjs — do not edit by hand.
//
// Copied from remotion-app/src/wrongshape/shapes.ts, which is the authored source and
// is shared with the Wrong-Shape Machine video. Edit it there, then run:
//
//     bun run sync
//
// Committed rather than gitignored so this project builds without the Remotion project
// checked out alongside it.

`;

const check = process.argv.includes("--check");

if (!existsSync(SOURCE)) {
  if (check) {
    // Nothing to compare against — the committed copy is all we have, and that is the
    // normal situation on a deploy runner. Not an error.
    console.log("source project not present; keeping the committed copy");
    process.exit(0);
  }
  console.error(`Cannot find the authored source at:\n  ${SOURCE}`);
  process.exit(1);
}

const wanted = HEADER + readFileSync(SOURCE, "utf8");

if (check) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current === wanted) {
    console.log("src/shared/shapes.ts is up to date");
    process.exit(0);
  }
  console.error(
    "src/shared/shapes.ts is STALE.\nRun `bun run sync` and commit the result.",
  );
  process.exit(1);
}

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT, wanted, "utf8");
console.log(`synced ${SOURCE}\n    -> src/shared/shapes.ts`);
